services:
  vanilla-server:
    build:
      context: server/vanilla/.
    container_name: vanilla-server
    ports:
      - 7777:7777 # Default Terraria server port
    environment:
      - WORLD_NAME=world
      - WORLD_SIZE=2 # 1=small, 2=medium, 3=large
      - WORLD_SEED=
      - PASSWORD=
      - DIFFICULTY=0 # 0=normal, 1=expert, 2=master, 3=journey
      - MAX_PLAYERS=8
    volumes:
      - vanilla-worlds:/terraria-server/worlds
    profiles: [vanilla]
    restart: unless-stopped
    tty: true
    stdin_open: true

volumes:
  vanilla-worlds:
    driver: local
