services:
  terraria-server:
    build:
      context: .
      dockerfile: server/vanilla/1.4.4.9/Dockerfile
    container_name: terraria-server
    ports:
      - 7777:7777 # Default Terraria server port
    environment:
      - WORLD_NAME=world
      - WORLD_SIZE=2 # 1=small, 2=medium, 3=large
      - WORLD_SEED=
      - PASSWORD=
      - DIFFICULTY=0 # 0=normal, 1=expert, 2=master, 3=journey
      - MAX_PLAYERS=8
    volumes:
      - terraria-server-worlds:/terraria-server/worlds
    restart: unless-stopped
    tty: true
    stdin_open: true

volumes:
  terraria-server-worlds:
    driver: local
