#cloud-config

disk_setup:
  /dev/sdb:
    table_type: gpt
    layout: true
    overwrite: false

fs_setup:
  - device: /dev/sdb1
    filesystem: ext4
    label: data
    overwrite: false

mounts:
  - [/dev/sdb1, /mnt/data]

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common

runcmd:
  - >
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg
    | apt-key add -
  - >
    add-apt-repository
    "deb [arch=$(dpkg --print-architecture)] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - apt-get update -y
  - >
    apt-get install -y
    docker-ce
    docker-ce-cli
    containerd.io
    docker-buildx-plugin
    docker-compose-plugin
  - systemctl start docker
  - systemctl enable docker
  - chown -R ubuntu:ubuntu /mnt/data

groups:
  - docker

system_info:
  default_user:
    name: ubuntu
    groups: [adm, cdrom, dip, lxd, sudo, docker]

disable_root: true
ssh_pwauth: false
