# Prettier configuration file.
# https://prettier.io/docs/en/configuration.html

# Global formatting options.
printWidth: 80
tabWidth: 2
useTabs: false
singleQuote: false
semi: true
quoteProps: as-needed
trailingComma: all

# File specific formatting options.
overrides:
  - files:
      - "*.yml"
      - "*.yaml"
    options:
      printWidth: 120
